/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <librealsense2/rs.hpp>
/* Header for class com_spartronics4915_lib_sensors_T265Camera */

#ifndef _Included_com_spartronics4915_lib_sensors_T265Camera
#define _Included_com_spartronics4915_lib_sensors_T265Camera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    startCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_startCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    stopCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_stopCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_free
  (JNIEnv *, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    newCamera
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_newCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    exportRelocalizationMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_exportRelocalizationMap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    loadRelocalizationMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_loadRelocalizationMap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    setOdometryInfo
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_setOdometryInfo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    sendOdometryRaw
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_sendOdometryRaw
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif

class deviceAndSensors
{
  public:
    deviceAndSensors(rs2::tm2 *dev, rs2::wheel_odometer *odom, rs2::pose_sensor *pose, std::function<void (rs2::frame)> *cb) : device(dev), wheelOdometrySensor(odom), poseSensor(pose), frameConsumerCallback(cb)
    {
    }

    ~deviceAndSensors()
    {
        delete device;
        delete wheelOdometrySensor;
        delete poseSensor;
        delete frameConsumerCallback;
    }

    const rs2::tm2 *device;
    rs2::wheel_odometer *wheelOdometrySensor;
    rs2::pose_sensor *poseSensor;
    std::function<void (rs2::frame)> *frameConsumerCallback;
};

deviceAndSensors *getDeviceFromClass(JNIEnv *env, jobject thisObj);

void ensureCache(JNIEnv *env, jobject thisObj);