/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spartronics4915_lib_sensors_T265Camera */

#ifndef _Included_com_spartronics4915_lib_sensors_T265Camera
#define _Included_com_spartronics4915_lib_sensors_T265Camera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    newCamera
 * Signature: (Ljava/util/function/Supplier;)J
 */
JNIEXPORT jlong JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_newCamera
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    startCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_startCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    stopCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_stopCamera
  (JNIEnv *, jobject);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    sendOdometryRaw
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_sendOdometryRaw
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    loadRelocalizationMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_loadRelocalizationMap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    setOdometryInfo
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_setOdometryInfo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_spartronics4915_lib_sensors_T265Camera
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spartronics4915_lib_sensors_T265Camera_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_spartronics4915_lib_sensors_T265Camera_CameraJNIException */

#ifndef _Included_com_spartronics4915_lib_sensors_T265Camera_CameraJNIException
#define _Included_com_spartronics4915_lib_sensors_T265Camera_CameraJNIException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_spartronics4915_lib_sensors_T265Camera_CameraJNIException_serialVersionUID
#define com_spartronics4915_lib_sensors_T265Camera_CameraJNIException_serialVersionUID -3042686055658047285LL
#undef com_spartronics4915_lib_sensors_T265Camera_CameraJNIException_serialVersionUID
#define com_spartronics4915_lib_sensors_T265Camera_CameraJNIException_serialVersionUID -3387516993124229948LL
#undef com_spartronics4915_lib_sensors_T265Camera_CameraJNIException_serialVersionUID
#define com_spartronics4915_lib_sensors_T265Camera_CameraJNIException_serialVersionUID -7034897190745766939LL
#ifdef __cplusplus
}
#endif
#endif
